//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monografia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monografia()
        {
            this.Estudiante = new HashSet<Estudiante>();
            this.Pro_Mon = new HashSet<Pro_Mon>();
        }
    
        public int IdMonografia { get; set; }
        public string CodigoMonografia { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> FechaDefendida { get; set; }
        public Nullable<int> NotaDefensa { get; set; }
        public Nullable<int> TiempoOtorgado { get; set; }
        public Nullable<int> TiempoDeDefensa { get; set; }
        public Nullable<int> TiempoPreguntaYRespuesta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiante> Estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_Mon> Pro_Mon { get; set; }
    }
}
